name: Dependency Scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  generate-nodejs-sbom:
    if: github.repository == 'launchdarkly/integration-framework-private'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: launchdarkly/common-actions/init@main

      - name: Generate SBOM
        uses: launchdarkly/common-actions/dependency-scan/generate-sbom@main
        with:
          types: 'nodejs'

  evaluate-policy:
    runs-on: ubuntu-latest
    if: github.repository == 'launchdarkly/integration-framework-private'
    needs:
      - generate-nodejs-sbom
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate SBOM Policy
        uses: launchdarkly/common-actions/dependency-scan/evaluate-policy@main
        with:
          artifacts-pattern: bom-*
